"""Added account table

Revision ID: af224591f223
Revises: 
Create Date: 2022-08-02 23:34:08.210452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af224591f223'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=225), nullable=False),
    sa.Column('description', sa.VARCHAR(length=225), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_permission_name'), 'permission', ['name'], unique=True, schema='security')
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=225), nullable=False),
    sa.Column('description', sa.VARCHAR(length=225), nullable=False),
    sa.Column('access_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='security'
    )
    op.create_index(op.f('ix_security_role_name'), 'role', ['name'], unique=True, schema='security')
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True, comment='name of user'),
    sa.Column('middle_name', sa.String(), nullable=True, comment='middle name of user'),
    sa.Column('last_name', sa.String(), nullable=True, comment='last name of user'),
    sa.Column('email', sa.String(), nullable=False, comment='email'),
    sa.Column('username', sa.String(), nullable=True, comment='username'),
    sa.Column('hashed_password', sa.String(), nullable=False, comment='passwd'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='locked or unlocked'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_subscribed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('subscription_ends', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='users',
    comment='Table with all users'
    )
    op.create_index(op.f('ix_users_user_email'), 'user', ['email'], unique=True, schema='users')
    op.create_index(op.f('ix_users_user_last_name'), 'user', ['last_name'], unique=False, schema='users')
    op.create_index(op.f('ix_users_user_name'), 'user', ['name'], unique=False, schema='users')
    op.create_table('permission_x_role',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['security.permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['security.role.id'], ),
    sa.PrimaryKeyConstraint('permission_id', 'role_id'),
    schema='security'
    )
    op.create_table('user_x_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['security.role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='security'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_x_role', schema='security')
    op.drop_table('permission_x_role', schema='security')
    op.drop_index(op.f('ix_users_user_name'), table_name='user', schema='users')
    op.drop_index(op.f('ix_users_user_last_name'), table_name='user', schema='users')
    op.drop_index(op.f('ix_users_user_email'), table_name='user', schema='users')
    op.drop_table('user', schema='users')
    op.drop_index(op.f('ix_security_role_name'), table_name='role', schema='security')
    op.drop_table('role', schema='security')
    op.drop_index(op.f('ix_security_permission_name'), table_name='permission', schema='security')
    op.drop_table('permission', schema='security')
    # ### end Alembic commands ###
